import os.path


def map_unique_atomtypes(params_atom):
    """
    get unique atomtypes by (epsilon, sigma, atomic_number) to avoid duplicate atomtypes in [ atomtypes ] block of .top/.itp file
    name the unique atomtype by domd_xxx while xxx is the unique idx
    return unique_atomtypes: {atom_idx: atomtypes_name}
    """
    atomidx2typeset = {}
    unique_atomtypes = {}
    atomtype2atom = {}
    params_set = set()
    for atom_idx, o_atom in params_atom.items():
        key = (o_atom.epsilon, o_atom.sigma, o_atom.element)
        params_set.add(key)
        atomidx2typeset[atom_idx] = key
        atomtype2atom[key] = o_atom
    if len(params_set) >= 1000:
        d = 4
    else:
        d = 3
    type2name = {}
    for i, key in enumerate(params_set):
        type2name[key] = f"domd_{i:0>{d}d}"
        unique_atomtypes[f"domd_{i:0>{d}d}"] = atomtype2atom[key]
    atomidx2atomtypes = {}
    for atom_idx, key in atomidx2typeset.items():
        atomidx2atomtypes[atom_idx] = type2name[key]
    return unique_atomtypes, atomidx2atomtypes


def write_gro_file(output_path, coordinates, box_tensor, res_names=None, res_ids=None, atom_names=[]):
    """
    :: params:
        coordinates: Nx3 (unit A)
        res_names: N, residue name list
        res_ids: N residue index list
        box_tensor: length of 9 ordered in v1(x) v2(y) v3(z) v1(y) v1(z) v2(x) v2(z) v3(x) v3(y) (unit: A)
                    or length of 3 ordered in boxl_x, boxl_y, boxl_z
    """
    num_atoms = len(coordinates)
    if res_ids is None:
        res_ids = [0] * num_atoms
    if res_names is None:
        res_names = ['UNL'] * num_atoms

    # box_tensor : v1(x) v2(y) v3(z) v1(y) v1(z) v2(x) v2(z) v3(x) v3(y)
    if len(box_tensor) < 9:
        box_tensor = list(box_tensor) + [0.0] * (9 - len(box_tensor))
    tensor_nm = [x / 10.0 for x in box_tensor]

    # 判断是否为标准正交盒子 (非对角线元素极小)
    is_orthogonal = (
            abs(tensor_nm[3]) < 1e-4 and abs(tensor_nm[6]) < 1e-4 and
            abs(tensor_nm[4]) < 1e-4 and abs(tensor_nm[7]) < 1e-4 and
            abs(tensor_nm[5]) < 1e-4 and abs(tensor_nm[8]) < 1e-4
    )

    if is_orthogonal:
        box_line = f"{tensor_nm[0]:10.5f} {tensor_nm[1]:10.5f} {tensor_nm[2]:10.5f}\n"
    else:
        box_line = (
            f"{tensor_nm[0]:10.5f} {tensor_nm[4]:10.5f} {tensor_nm[8]:10.5f} "
            f"{tensor_nm[1]:10.5f} {tensor_nm[2]:10.5f} {tensor_nm[3]:10.5f} "
            f"{tensor_nm[6]:10.5f} {tensor_nm[7]:10.5f} {tensor_nm[5]:10.5f}\n"
        )

    with open(output_path, 'w', buffering=65536) as f:
        f.write("Generated by High-Performance MD Toolset (Restored Massive System)\n")
        f.write(f"{num_atoms:5d}\n")

        for i, res_id, r_name, a_name, (x, y, z) in zip(range(num_atoms), res_ids, res_names, atom_names, coordinates):
            res_id_safe = int(res_id) % 100000
            atom_id_safe = (i + 1) % 100000

            r_name = str(r_name)[:5]
            a_name = a_name[:5] if i < len(atom_names) else f"A{i + 1}"[:5]

            x_nm = x / 10.0
            y_nm = y / 10.0
            z_nm = z / 10.0

            f.write(f"{res_id_safe:5d}{r_name:<5}{a_name:>5}{atom_id_safe:5d}{x_nm:8.3f}{y_nm:8.3f}{z_nm:8.3f}\n")
        f.write(box_line)



def write_top_file(output_path, ff, res_names=None, res_ids=None):
    """
    工业级 GROMACS .top 拓扑文件写出器
    支持百万/千万级超大体系，支持 OPLS-AA 力场参数的原子类型自动去重。

    参数:
        output_path (str): filename of .top
        ff (ForceField): ForceField object
        res_names (list): residue name list
        res_ids (list): residue index list
        unique_atomtypes (dict, optional):  {atomtype_name: OPLSAtom}
        atomidx2atomtype (dict, optional):  {atom_idx: atomtype_name}
    """

    params_atom, params_bonded, params_improper = ff.params
    charges = ff.charges
    unique_atomtypes, atomidx2atomtype = map_unique_atomtypes(params_atom)

    bonds_list = []
    angles_list = []
    dihedrals_list = []

    num_atoms = len(params_atom)
    if res_ids is None:
        res_ids = [0]*num_atoms
    if res_names is None:
        res_names = ['UNL']*num_atoms

    for indices, item in params_bonded.items():
        if len(indices) == 2:
            bonds_list.append(item)
        elif len(indices) == 3:
            angles_list.append(item)
        elif len(indices) == 4:
            dihedrals_list.append(item)

    with open(output_path, 'w', buffering=65536) as f:
        f.write(";---------------------------------------------\n")
        f.write(";        Generated with ChemFAST\n")
        f.write(";            Hu-Jun Qian Lab\n")
        f.write(";       Author: lmy23@mails.jlu.edu.cn\n")
        f.write(";       OPLS Force Field from ChemFAST\n")
        f.write(";---------------------------------------------\n\n")
        f.write("[ defaults ]\n")
        f.write("; nbfunc        comb-rule       gen-pairs       fudgeLJ         fudgeQQ\n")
        f.write("  1             3               yes             0.5             0.5\n\n")

        f.write("[ atomtypes ]\n")
        f.write("; name   bond_type     mass       charge   ptype          sigma        epsilon\n")
        for a_type, o_atom in unique_atomtypes.items():
            f.write(
                f"  {a_type:<8} {o_atom.bond_type:<8} {o_atom.mass:>10.4f} {o_atom.charge:>8.4f} {o_atom.ptype:<3} {o_atom.sigma:>14.6e} {o_atom.epsilon:>14.6e}\n")
        f.write("\n")

        f.write("[ moleculetype ]\n")
        f.write("; Name            nrexcl\n")
        f.write("SystemMolecule    3\n\n")

        f.write("[ atoms ]\n")
        f.write(";   nr       type  resnr residue  atom   cgnr     charge       mass\n")

        for i, o_atom, r_num, r_name, a_charge in zip(range(len(res_ids)), params_atom, res_ids, res_names, charges):
            atom_idx = i + 1
            r_name = str(r_name)[:5]
            a_name = f"{o_atom.element}"
            f.write(
                f"{atom_idx:>6} {atomidx2atomtype[i]:>10} {r_num:>6} {r_name:>6} {a_name:>6} {atom_idx:>6} {a_charge:>10.4f} {o_atom.mass:>10.4f}\n")
        f.write("\n")

        if bonds_list:
            f.write("[ bonds ]\n")
            f.write(";  ai    aj funct            r0             k\n")
            for b in bonds_list:
                ai = b.indices[0] + 1
                aj = b.indices[1] + 1
                f.write(f"{ai:>5} {aj:>5} {b.ftype:>5} {b.r0:>14.6e} {b.k:>14.6e}\n")
            f.write("\n")

        if angles_list:
            f.write("[ angles ]\n")
            f.write(";  ai    aj    ak funct            t0             k\n")
            for a in angles_list:
                ai, aj, ak = a.indices[0] + 1, a.indices[1] + 1, a.indices[2] + 1
                f.write(
                    f"{ai:>5} {aj:>5} {ak:>5} {a.ftype:>5} {a.t0:>14.6e} {a.k:>14.6e}\n")
            f.write("\n")

        if dihedrals_list:
            f.write("[ dihedrals ]\n")
            f.write(
                ";  ai    aj    ak    al funct          c0            c1            c2            c3            c4            c5\n")
            for d in dihedrals_list:
                ai, aj, ak, al = d.indices[0] + 1, d.indices[1] + 1, d.indices[2] + 1, d.indices[3] + 1
                f.write(f"{ai:>5} {aj:>5} {ak:>5} {al:>5} {d.ftype:>5} "
                        f"{d.c0:>13.5e} {d.c1:>13.5e} {d.c2:>13.5e} {d.c3:>13.5e} {d.c4:>13.5e} {d.c5:>13.5e}\n")
            f.write("\n")

        if params_improper:
            f.write("; Improper\n")
            f.write(";  ai    aj    ak    al funct    (parameters)\n")
            for imp in params_improper.values():
                ai, aj, ak, al = imp.indices[0] + 1, imp.indices[1] + 1, imp.indices[2] + 1, imp.indices[3] + 1
                param_str = " ".join(f"{x:>14.6e}" if isinstance(x, (int, float)) else str(x) for x in imp.params)
                f.write(
                    f"{ai:>5} {aj:>5} {ak:>5} {al:>5} {imp.ftype:>5} {param_str}\n")
            f.write("\n")

        if dihedrals_list:
            f.write("[ pairs ]\n")
            f.write(";  ai    aj    funct\n")
            for d in dihedrals_list:
                ai, aj = d.indices[0] + 1, d.indices[3] + 1
                f.write(f"{ai:>5} {aj:>5}    1\n")
                # f.write(f"{d.indices[0]:>5} {d.indices[3]:>5} 1\n")

        f.write("[ system ]\n")
        f.write("Automated Parametrized Molecular System\n\n")

        f.write("[ molecules ]\n")
        f.write("; Compound        #mols\n")
        f.write("SystemMolecule    1\n")


def write_itp_file(output_path, ff, res_names=None, res_ids=None, mol_name="MOL", unique_atomtypes=None, atomidx2atomtype=None,
                   write_atomtypes=False):
    """
    :: params:
        output_path (str): file name of .itp
        ff (ForceField): ForceField object
        res_names (list): list of names of residues
        res_ids (list): list of indices of residues
        mol_name (str): list of molecule names
    """
    params_atom, params_bonded, params_improper = ff.params
    charges = ff.charges
    if unique_atomtypes is None and atomidx2atomtype is None:
        unique_atomtypes, atomidx2atomtype = map_unique_atomtypes(params_atom)

    num_atoms = len(params_atom)
    if res_ids is None:
        res_ids = [1] * num_atoms
    if res_names is None:
        res_names = ['UNL'] * num_atoms

    bonds_list = []
    angles_list = []
    dihedrals_list = []

    for indices, item in params_bonded.items():
        if len(indices) == 2:
            bonds_list.append(item)
        elif len(indices) == 3:
            angles_list.append(item)
        elif len(indices) == 4:
            dihedrals_list.append(item)

    with open(output_path, 'w', buffering=65536) as f:
        f.write(";---------------------------------------------\n")
        f.write(";        Generated with ChemFAST\n")
        f.write(";            Hu-Jun Qian Lab\n")
        f.write(";       Author: lmy23@mails.jlu.edu.cn\n")
        f.write(";       OPLS Force Field from ChemFAST\n")
        f.write(";---------------------------------------------\n\n")
        if write_atomtypes:
            f.write("[ defaults ]\n")
            f.write("; nbfunc        comb-rule       gen-pairs       fudgeLJ         fudgeQQ\n")
            f.write("  1             3               yes             0.5             0.5\n\n")

            f.write("[ atomtypes ]\n")
            f.write("; name   bond_type     mass       charge   ptype          sigma        epsilon\n")
            for a_type, o_atom in unique_atomtypes.items():
                f.write(
                    f"  {a_type:<8} {o_atom.bond_type:<8} {o_atom.mass:>10.4f} {o_atom.charge:>8.4f} {o_atom.ptype:<3} {o_atom.sigma:>14.6e} {o_atom.epsilon:>14.6e}\n")
            f.write("\n")

        f.write("[ moleculetype ]\n")
        f.write("; Name            nrexcl\n")
        f.write(f"{mol_name:<16} 3\n\n")

        f.write("[ atoms ]\n")
        f.write(";   nr       type  resnr residue  atom   cgnr     charge       mass\n")
        for i, o_atom, r_num, r_name, a_charge in zip(range(len(res_ids)),
                                                      params_atom, res_ids,
                                                      res_names, charges):
            atom_idx = i + 1
            r_name = str(r_name)[:5]
            a_name = f"{o_atom.element}"
            f.write(
                f"{atom_idx:>6} {atomidx2atomtype[i]:>10} {r_num:>6} {r_name:>6} {a_name:>6} {atom_idx:>6} {a_charge:>10.4f} {o_atom.mass:>10.4f}\n")
        f.write("\n")

        # --- [ bonds ] 块 ---
        if bonds_list:
            f.write("[ bonds ]\n")
            f.write(";  ai    aj funct            r0             k\n")
            for b in bonds_list:
                ai = b.indices[0] + 1
                aj = b.indices[1] + 1
                f.write(f"{ai:>5} {aj:>5} {b.ftype:>5} {b.r0:>14.6e} {b.k:>14.6e}\n")
            f.write("\n")

        if angles_list:
            f.write("[ angles ]\n")
            f.write(";  ai    aj    ak funct            t0             k\n")
            for a in angles_list:
                ai, aj, ak = a.indices[0] + 1, a.indices[1] + 1, a.indices[2] + 1
                f.write(
                    f"{ai:>5} {aj:>5} {ak:>5} {a.ftype:>5} {a.t0:>14.6e} {a.k:>14.6e}\n")
            f.write("\n")

        if dihedrals_list:
            f.write("[ dihedrals ]\n")
            f.write(
                ";  ai    aj    ak    al funct          c0            c1            c2            c3            c4            c5\n")
            for d in dihedrals_list:
                ai, aj, ak, al = d.indices[0] + 1, d.indices[1] + 1, d.indices[2] + 1, d.indices[3] + 1
                f.write(f"{ai:>5} {aj:>5} {ak:>5} {al:>5} {d.ftype:>5} "
                        f"{d.c0:>13.5e} {d.c1:>13.5e} {d.c2:>13.5e} {d.c3:>13.5e} {d.c4:>13.5e} {d.c5:>13.5e}\n")
            f.write("\n")

        if params_improper:
            f.write("; Improper\n")
            f.write(";  ai    aj    ak    al funct    (parameters)\n")
            for imp in params_improper.values():
                ai, aj, ak, al = imp.indices[0] + 1, imp.indices[1] + 1, imp.indices[2] + 1, imp.indices[3] + 1
                param_str = " ".join(f"{x:>14.6e}" if isinstance(x, (int, float)) else str(x) for x in imp.params)
                f.write(
                    f"{ai:>5} {aj:>5} {ak:>5} {al:>5} {imp.ftype:>5} {param_str}\n")
            f.write("\n")

        if dihedrals_list:
            f.write("[ pairs ]\n")
            f.write(";  ai    aj    funct\n")
            for d in dihedrals_list:
                ai, aj = d.indices[0] + 1, d.indices[3] + 1
                f.write(f"{ai:>5} {aj:>5}     1\n")


def write_atomtypes_head(output_path, unique_atomtypes, write_defaults=False):
    """
    write [ atomtypes ] head information for .top or .itp
    """
    with open(output_path, 'w', buffering=65536) as f:
        if write_defaults:
            f.write("; ==================================================================\n")
            f.write("; Master topology file generated by ChemFAST\n")
            f.write("; ==================================================================\n\n")

            # --- [ defaults ] block ---
            # Standard OPLS-AA configuration: combination rule 3, 1-4 scaling factors
            f.write("[ defaults ]\n")
            f.write(
                "; nbfunc        comb-rule       gen-pairs       fudgeLJ         fudgeQQ\n")
            f.write(
                "  1             3               yes             0.5             0.5\n\n")
        f.write("[ atomtypes ]\n")
        f.write("; name   bond_type     mass       charge   ptype          sigma        epsilon\n")
        for a_type, o_atom in unique_atomtypes.items():
            f.write(
                f"  {a_type:<8} {o_atom.bond_type:<8} {o_atom.mass:>10.4f} {o_atom.charge:>8.4f} {o_atom.ptype:<3} {o_atom.sigma:>14.6e} {o_atom.epsilon:>14.6e}\n")
        f.write("\n")


def write_top_file_with_includes(output_path, atomtypes_itp, mol_itp_mapping, mol_counts, mol_names,
                                 system_name="ChemFAST Parametrized Molecular System"):
    """
    Master GROMACS .top file generator using the #include format.
    Assembles global defaults, atomtypes, and molecule-specific topologies.

    Parameters:
        output_path (str): Target path for the generated master .top file.
        atomtypes_itp (str): File path or filename of the shared atomtypes itp file.
        mol_itp_mapping (dict): Mapping of molecule identifier/name to its .itp file path.
                                e.g., {0: "top/mol1.itp", 1: "top/mol2.itp"}
        mol_counts (dict): Mapping of molecule identifier/name to its stoichiometric count.
                           e.g., {0: 100, 1: 50}
        mol_names (dict): Mapping of molecule identifier/name to its descriptive name.
                           e.g., {0: "Water", 1: "Ethanol"}
        system_name (str): Character description of the molecular system.
    """
    atomtypes_itp = os.path.basename(atomtypes_itp)  # Ensure only the filename is used in the include directive
    mol_idx = sorted(mol_itp_mapping.keys())
    for mol_id in mol_idx:
        mol_itp_mapping[mol_id] = os.path.basename(mol_itp_mapping[mol_id])  # Ensure only the filename is used
    with open(output_path, 'w', buffering=65536) as f:
        f.write("; ==================================================================\n")
        f.write("; Master topology file generated by ChemFAST\n")
        f.write("; ==================================================================\n\n")

        # --- [ defaults ] block ---
        # Standard OPLS-AA configuration: combination rule 3, 1-4 scaling factors
        f.write("[ defaults ]\n")
        f.write("; nbfunc        comb-rule       gen-pairs       fudgeLJ         fudgeQQ\n")
        f.write("  1             3               yes             0.5             0.5\n\n")

        # --- Include atomtypes ---
        f.write("; Include global non-bonded parameters\n")
        f.write(f'#include "{atomtypes_itp}"\n\n')

        # --- Include molecule topologies ---
        f.write("; Include individual molecule bonded topologies\n")
        for mol_id in mol_idx:
            itp_path = mol_itp_mapping[mol_id]
            f.write(f'#include "{itp_path}"\n')
        f.write("\n")

        # --- [ system ] block ---
        f.write("[ system ]\n")
        f.write(f"{system_name}\n\n")

        # --- [ molecules ] block ---
        f.write("[ molecules ]\n")
        f.write("; Compound        #mols\n")
        for mol_id in mol_idx:
            count = mol_counts[mol_id]
            mol_name = mol_names[mol_id]
            f.write(f"{mol_name:<16} {count}\n")


import os


def write_list_itp_files(output_path, forcefields, molecule_name, list_res_names=[], list_res_ids=[]):
    '''
    :: params
        output_path: list, [MOL_0.itp, MOL_1.itp, ...]
        forcefields: list, [FF object, FF object, ...]
        molecule_name: list, [MOL_0, MOL_1, ...]
        list_res_names: list, [ [res1, res2, res1, ...] , ...]
        list_res_ids: list, [ [0, 0, 1, ... ], ...]
    :: output
        1. write all itp files in output_path
        2. atomtypes.itp
    '''
    global_params_set = set()
    atomtype2atom = {}

    for ff in forcefields:
        params_atom, _, _ = ff.params
        for atom_idx, o_atom in params_atom.items():
            key = (o_atom.epsilon, o_atom.sigma, o_atom.element)
            global_params_set.add(key)
            if key not in atomtype2atom:
                atomtype2atom[key] = o_atom

    if len(global_params_set) >= 1000:
        d = 4
    else:
        d = 3

    global_unique_atomtypes = {}
    type2name = {}

    for i, key in enumerate(sorted(global_params_set)):
        type_name = f"domd_{i:0>{d}d}"
        type2name[key] = type_name
        global_unique_atomtypes[type_name] = atomtype2atom[key]

    if len(list_res_names) < len(molecule_name):
        list_res_names = list_res_names + [None] * (len(molecule_name) - len(list_res_names))
    if len(list_res_ids) < len(molecule_name):
        list_res_ids = list_res_ids + [None] * (len(molecule_name) - len(list_res_ids))
    for out_p, ff, mol_n, default_res_names, default_res_ids in zip(output_path, forcefields, molecule_name, list_res_names, list_res_ids):
        params_atom, _, _ = ff.params
        local_atomidx2atomtype = {}

        for atom_idx, o_atom in params_atom.items():
            key = (o_atom.epsilon, o_atom.sigma, o_atom.element)
            local_atomidx2atomtype[atom_idx] = type2name[key]

        num_atoms = len(params_atom)
        if default_res_names is None or len(default_res_names) < num_atoms:
            default_res_names = ['UNL'] * num_atoms
        if default_res_ids is None or len(default_res_ids) < num_atoms:
            default_res_ids = [1] * num_atoms

        write_itp_file(
            output_path=out_p,
            ff=ff,
            res_names=default_res_names,
            res_ids=default_res_ids,
            mol_name=mol_n,
            unique_atomtypes=global_unique_atomtypes,
            atomidx2atomtype=local_atomidx2atomtype,
            write_atomtypes=False
        )

    if output_path:
        base_dir = os.path.dirname(output_path[0])
        atomtypes_path = os.path.join(base_dir, "atomtypes.itp") if base_dir else "atomtypes.itp"
    else:
        atomtypes_path = "atomtypes.itp"

    write_atomtypes_head(atomtypes_path, global_unique_atomtypes, write_defaults=True)
